# Progress Screen Constants
PROGRESS_SCREEN_PERCENT_DONE = "percent_done"
PROGRESS_SCREEN_MESSAGE_LIST = "message_list"
PROGRESS_SCREEN_DATA_DICT_KEYS = [PROGRESS_SCREEN_PERCENT_DONE, PROGRESS_SCREEN_MESSAGE_LIST]

ELAPSED_TIME_PREFIX = "Elapsed time: "
ESTIMATED_TIME_LEFT_PREFIX = "Estimated time left: "
